[build]
  command = "npm run build"
  publish = "dist"
  node_version = "14"  # รูปแบบถูกต้องโดยไม่มีคอมม่าที่เกินหรือค่าที่หายไป

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301
